name: Deploy Documentation on Release

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  docs:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: macos-latest
    steps:
      - name: Check out diffpy.fourigui
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches branches and tags

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: build
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.13

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: IInstall diffpy.fourigui and docs requirements
        run: |
          conda install --file requirements/conda.txt
          conda install --file requirements/docs.txt
          if ${{ inputs.c_extension }}; then
            conda install --file requirements/build.txt
          fi
          python -m pip install . --no-deps

      - name: build documents
        run: make -C doc html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
